# Generated by Django 6.0.2 on 2026-02-20 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='cliente',
        ),
        migrations.AddField(
            model_name='comanda',
            name='pedido',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='app.pedido'),
            preserve_default=False,
        ),
    ]
