# Generated by Django 6.0.2 on 2026-02-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='menu',
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_documento',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_de_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero_documento',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_de_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_documento',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_de_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='estado',
            field=models.CharField(choices=[('En preparación', 'En preparación'), ('Listo', 'Listo'), ('Entregado', 'Entregado')], default='En preparación', max_length=15),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('En preparación', 'En preparación'), ('Listo', 'Listo'), ('Entregado', 'Entregado')], default='En preparación', max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En preparación', 'En preparación'), ('Listo', 'Listo'), ('Entregado', 'Entregado')], default='En preparación', max_length=15),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
