# Generated by Django 6.0.2 on 2026-02-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cliente_cedula_cliente_numero_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='plato',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='recetas',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comanda',
            options={},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.AlterField(
            model_name='comanda',
            name='estado',
            field=models.CharField(choices=[('En preparación', 'En preparación'), ('Listo', 'Listo'), ('Entregado', 'Entregado')], default='En preparación', max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En preparación', 'En preparación'), ('Listo', 'Listo'), ('Entregado', 'Entregado')], default='En preparación', max_length=15),
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='insumo',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='Plato',
        ),
    ]
