# Generated by Django 6.0.2 on 2026-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cliente_cedula_cliente_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
