# Generated by Django 6.0.2 on 2026-02-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cliente_cedula_remove_mesa_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP'), ('Frecuente', 'Frecuente')], default='Regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En preparación', 'En preparación'), ('Entregado', 'Entregado')], default='En preparación', max_length=15),
        ),
    ]
