# Generated by Django 6.0.2 on 2026-02-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_fecha_ingreso_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('g', 'Gramo (g)'), ('l', 'Litro (L)'), ('ml', 'Mililitro (ml)'), ('m', 'Metro (m)'), ('cm', 'Centímetro (cm)'), ('unidad', 'Unidad')], default='unidad', max_length=20),
        ),
    ]
