# Generated by Django 6.0.2 on 2026-02-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cliente_cedula_cliente_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.IntegerField(verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor'),
        ),
    ]
