# Generated by Django 6.0.1 on 2026-02-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_plato_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
