# Generated by Django 6.0.2 on 2026-02-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_insumo_unidad_alter_insumo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='valor',
            field=models.CharField(max_length=100),
        ),
    ]
