# Generated by Django 6.0.2 on 2026-02-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('', 'Seleccione una unidad 🡇'), ('kg', 'Kilogramo (kg)'), ('g', 'Gramo (g)'), ('l', 'Litro (L)'), ('ml', 'Mililitro (ml)'), ('m', 'Metro (m)'), ('cm', 'Centímetro (cm)')], default='unidad', max_length=20),
        ),
    ]
