# Generated by Django 6.0.2 on 2026-02-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cliente_tipo_cliente_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
