# Generated by Django 6.0.2 on 2026-02-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_producto_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='verificar_contrasena',
        ),
    ]
